### ISSUE TITLE
Instead of skipping steps, mark them skipped using a conditional, so they still show up in the UI

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#167]
![image](https://user-images.githubusercontent.com/97427/99209014-00f7af80-2827-11eb-909c-be7837499194.png)

**Comment by dominics** [comment]
```yaml
steps:
  - label: ":package:"
    if: "false // reason"
```
