### ISSUE TITLE
Support exclusion from PIPELINE_RUN_ALL

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#195]
Some sub-pipelines might only be triggered in certain circumstances, e.g. when PIPELINE_RUN_<component> or PIPELINE_RUN_ONLY are given. One use case I've seen for this is 'task' pipelines, run by schedules, where the task wants to reused some of the monofo build, but doesn't want to ever be pulled in by PIPELINE_RUN_ALL

This might be `task: true` or `runs_on: { all: false }` or similar:

```
monorepo:
  name: some-task
  task: true
  expects:
    - node-modules.tar.lz4
    - typescript.tar.lz4
```
