### ISSUE TITLE
Overeager replacement of dependency in pipeline with no `expects`

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#267]
I have a pipeline that's roughly like this:

```yaml
monorepo:
  pure: true
  matches:
    - "**/package.json"
    - yarn.lock
    - scripts/yarn-install
  produces: node-modules.tar.lz4
    
steps:
  - name: ":nodejs: Install"
    key: node-modules
    depends_on: node-image
    command: scripts/yarn-install
```

Even though this pipeline doesn't declare any `expects`, when we skip the `node-image` containing pipeline, we also make this step wait for the inject artifacts step. That must be unnecessary: this pipeline declares no `expects` so it can't _need_ to wait for artifacts to be pulled from previous builds (and if it does, it should declare that fact).

Removing this unnecessary depends_on replacement would allow this step to run immediately, rather than waiting for inject-artifacts.
