### ISSUE TITLE
Support setting Github statuses for skipped components

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#34]
https://developer.github.com/v3/repos/statuses/

maybe configured like

```yaml
monorepo:
  excluded:
    statuses: ['foo/bar']
```
